class Captionqueue < Formula
  include Language::Python::Virtualenv

  desc "Drop a video + SRT into a folder, get back a captioned MP4"
  homepage "https://github.com/chrisreddington/captionqueue"
  url "PLACEHOLDER_SDIST_URL"
  sha256 "PLACEHOLDER_SHA256"
  license "MIT"
  version "0.0.0"

  depends_on "ffmpeg"
  depends_on "python@3.12"

  # Python resource blocks are generated by `brew update-python-resources`
  # during the release-dispatch workflow. Do not edit by hand.

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "captionqueue", shell_output("#{bin}/captionqueue --help")
  end
end
